#!/bin/bash

set -ex

echo "This command is run to configure an Orange-Box Openstack deployment"

obnum=`hostname | cut -c 10- -`

PKGS=" python-keystone python-neutronclient python-novaclient python-glanceclient python-openstackclient"
dpkg -l $PKGS > /dev/null || sudo apt-get install -y $PKGS

NEUTRON_DNS="172.27.$((obnum+3)).254"

NEUTRON_EXT_NET_NAME="extnet"
NEUTRON_EXT_NET_GW="172.27.$((obnum+3)).254"
NEUTRON_EXT_NET_CIDR="172.27.$((obnum+2)).0/23"
NEUTRON_EXT_NET_FLOAT_RANGE_START="172.27.$((obnum+3)).150"
NEUTRON_EXT_NET_FLOAT_RANGE_END="172.27.$((obnum+3)).200"

NEUTRON_FIXED_NET_CIDR="192.168.$((obnum)).0/24"
NEUTRON_FIXED_NET_NAME="tenant"

keystone=$(juju status keystone | grep keystone/0 | awk '{print $5}' )

echo "#!/bin/bash
export OS_USERNAME=admin
export OS_PASSWORD=admin
export OS_TENANT_NAME=admin
export OS_REGION_NAME=RegionOne
export OS_AUTH_URL=${OS_AUTH_PROTOCOL:-http}://`juju run --unit keystone/0 'unit-get private-address'`:5000/v2.0
" > nova.rc

chmod +x neutron-ext-net
chmod +x neutron-tenant-net

source nova.rc

#EXT NET 
./neutron-ext-net -g $NEUTRON_EXT_NET_GW -c $NEUTRON_EXT_NET_CIDR  -f $NEUTRON_EXT_NET_FLOAT_RANGE_START:$NEUTRON_EXT_NET_FLOAT_RANGE_END $NEUTRON_EXT_NET_NAME

#PRIVATE NET
./neutron-tenant-net -t admin -r provider-router -N $NEUTRON_DNS private $NEUTRON_FIXED_NET_CIDR

#Configure the default security group to allow ICMP and SSH
openstack security group rule create --proto icmp default
#openstack security group rule create --proto tcp --dst-port 22 default
#openstack security group rule create --proto tcp --dst-port 80 default
#openstack security group rule create --proto tcp --dst-port 8080 default
#openstack security group rule create --proto tcp --dst-port 443 default
#openstack security group rule create --proto tcp --dst-port 3389 default
##Port openning for IMS/SiP Traffic
#openstack security group rule create --proto tcp --dst-port 5060 default
#openstack security group rule create --proto tcp --dst-port 4060 default
#openstack security group rule create --proto udp --dst-port 5060 default
#openstack security group rule create --proto udp --dst-port 4060 default
openstack security group rule create --proto tcp --dst-port 1:65535 default
openstack security group rule create --proto udp --dst-port 1:65535 default

#Upload a default SSH key
openstack keypair create  --public-key ~/.ssh/id_rsa.pub default

#Remove the m1.tiny as it is too small for Ubuntu.
openstack flavor create m1.small --id auto --ram 4096 --disk 30 --vcpus 2
openstack flavor create m1.medium --id auto --ram 8192 --disk 35 --vcpus 2
openstack flavor create m1.large --id auto --ram 12288 --disk 40 --vcpus 4
openstack flavor create m1.xlarge --id auto --ram 16384 --disk 45 --vcpus 4

#Modify quotas for the tenant to allow large deployments
openstack quota  set --ram 204800 --cores 200 --instances 100 admin
neutron quota-update --security-group 100 --security-group-rule 500 

#Upload vnf images to glance
glance image-create --name=openims --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/openims.img
glance image-create --name=ubuntu_16.04 --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/xenial-server-cloudimg-amd64-disk1.img
glance image-create --name=ubuntu_14.04 --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/trusty-server-cloudimg-amd64-disk1.img
glance image-create --name=cirros_0.3.5 --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/cirros-0.3.5-x86_64-disk.img
#glance image-create --name=centos_7 --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/CentOS-7-x86_64-GenericCloud.qcow2
sudo cp nova.rc /home/jenkins/joid_config/admin-openrc
exit
