#!/bin/bash
#Author:  Fatih Eyup Nar <fenar>

set -ex

echo "This command is run to configure an Orange-Box Openstack deployment"

obnum=`hostname | cut -c 10- -`

PKGS=" python-keystone python-neutronclient python-novaclient python-glanceclient python-openstackclient python-swiftclient"
dpkg -l $PKGS > /dev/null || sudo apt-get install -y $PKGS

NEUTRON_DNS="172.27.$((obnum+3)).254"

NEUTRON_EXT_NET_NAME="ext_net"
NEUTRON_EXT_NET_GW="172.27.$((obnum+3)).254"
NEUTRON_EXT_NET_CIDR="172.27.$((obnum+2)).0/23"
NEUTRON_EXT_NET_FLOAT_RANGE_START="172.27.$((obnum+3)).150"
NEUTRON_EXT_NET_FLOAT_RANGE_END="172.27.$((obnum+3)).200"

NEUTRON_FIXED_NET_CIDR="192.168.$((obnum)).0/24"
NEUTRON_FIXED_NET_NAME="admin_net"

keystone=$(juju status keystone | grep keystone/0 | awk '{print $5}' )

echo "#!/bin/bash
export OS_USERNAME=admin
export OS_PASSWORD=admin
export OS_TENANT_NAME=admin
export OS_REGION_NAME=RegionOne
export OS_AUTH_URL=${OS_AUTH_PROTOCOL:-http}://`juju run --unit keystone/0 'unit-get private-address'`:5000/v2.0
" > nova.rc

chmod +x neutron-ext-net
chmod +x neutron-tenant-net

source nova.rc

#EXT NET
./neutron-ext-net -g $NEUTRON_EXT_NET_GW -c $NEUTRON_EXT_NET_CIDR  -f $NEUTRON_EXT_NET_FLOAT_RANGE_START:$NEUTRON_EXT_NET_FLOAT_RANGE_END ext_net

#PRIVATE NET
./neutron-tenant-net -t admin -r provider-router -N $NEUTRON_DNS private $NEUTRON_FIXED_NET_CIDR

#Configure the default security group to allow ICMP and SSH
openstack security group rule create --proto icmp default
# opening all ports as the current setup requires several ports to be open
openstack security group rule create --proto udp --dst-port 1:65535 default
openstack security group rule create --proto tcp --dst-port 1:65535 default

#Upload a default SSH key
openstack keypair create  --public-key ~/.ssh/id_rsa.pub default

#Modify quotas for the tenant to allow large deployments
openstack quota  set --ram 204800 --cores 200 --instances 100 admin
neutron quota-update --security-group 100 --security-group-rule 500
nova quota-update --ram 204800 --cores 200 --instances 100 admin

#upload images needed by OB otherwise download from marketplace would be very slow
# image link: http://marketplace.openbaton.org:8082/api/v1/images/52e2ccc0-1dce-4663-894d-28aab49323aa/img
glance image-create --name=openims --visibility=public --container-format=ovf --disk-format=qcow2 <  /srv/data/openims.img

#Adding Host Aggregates for Exclusive LXD

for i in ` openstack hypervisor list -f value  -c "Hypervisor Hostname"` ; do echo -n $i, ; openstack hypervisor show $i -c hypervisor_type -f value ; done > hypervisor-hosts

LXD_HOST=`grep lxd hypervisor-hosts  | cut -d "," -f 1 `
#KVM_HOST=`grep QEMU hypervisor-hosts  | cut -d "," -f 1 `
rm -rf hypervisor-hosts

nova aggregate-create lxd-aggregate
nova aggregate-set-metadata 1 exclusive=true
nova aggregate-set-metadata 1 max_instances_per_host=1
#nova aggregate-create kvm-aggregate

for lxdnodes in ${LXD_HOST[@]}
do
    nova aggregate-add-host lxd-aggregate ${lxdnodes:0:11}
done

#for kvmnodes in ${KVM_HOST[@]}
#do
#    nova aggregate-add-host kvm-aggregate ${kvmnodes:0:11}
#done

nova flavor-create --is-public true k.small 444 4096 10 2
nova flavor-create --is-public true l.small 333 4096 10 2
nova flavor-key 333 set aggregate_instance_extra_specs:exclusive=true
exit
